# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/TriKhiem/python-app/ui/field_schedule.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FieldSchedule(object):
    def setupUi(self, FieldSchedule):
        FieldSchedule.setObjectName("FieldSchedule")
        FieldSchedule.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(FieldSchedule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_widget = QtWidgets.QWidget(parent=FieldSchedule)
        self.header_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.header_widget.setStyleSheet("QWidget#header_widget {\n"
"    background-color: #4CAF50;\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.header_widget.setObjectName("header_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.field_name = QtWidgets.QLabel(parent=self.header_widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.field_name.setFont(font)
        self.field_name.setObjectName("field_name")
        self.verticalLayout_2.addWidget(self.field_name)
        self.field_details = QtWidgets.QLabel(parent=self.header_widget)
        self.field_details.setObjectName("field_details")
        self.verticalLayout_2.addWidget(self.field_details)
        self.verticalLayout.addWidget(self.header_widget)
        self.date_widget = QtWidgets.QWidget(parent=FieldSchedule)
        self.date_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.date_widget.setObjectName("date_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.date_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date_label = QtWidgets.QLabel(parent=self.date_widget)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout.addWidget(self.date_label)
        self.date_picker = QtWidgets.QDateEdit(parent=self.date_widget)
        self.date_picker.setMinimumSize(QtCore.QSize(200, 30))
        self.date_picker.setCalendarPopup(True)
        self.date_picker.setObjectName("date_picker")
        self.horizontalLayout.addWidget(self.date_picker)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.date_widget)
        self.schedule_scroll = QtWidgets.QScrollArea(parent=FieldSchedule)
        self.schedule_scroll.setWidgetResizable(True)
        self.schedule_scroll.setObjectName("schedule_scroll")
        self.schedule_content = QtWidgets.QWidget()
        self.schedule_content.setObjectName("schedule_content")
        self.schedule_layout = QtWidgets.QVBoxLayout(self.schedule_content)
        self.schedule_layout.setSpacing(5)
        self.schedule_layout.setObjectName("schedule_layout")
        self.schedule_scroll.setWidget(self.schedule_content)
        self.verticalLayout.addWidget(self.schedule_scroll)
        self.book_button = QtWidgets.QPushButton(parent=FieldSchedule)
        self.book_button.setMinimumSize(QtCore.QSize(0, 40))
        self.book_button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}")
        self.book_button.setObjectName("book_button")
        self.verticalLayout.addWidget(self.book_button)

        self.retranslateUi(FieldSchedule)
        QtCore.QMetaObject.connectSlotsByName(FieldSchedule)

    def retranslateUi(self, FieldSchedule):
        _translate = QtCore.QCoreApplication.translate
        self.field_name.setText(_translate("FieldSchedule", "Field Name"))
        self.field_details.setText(_translate("FieldSchedule", "Field Details"))
        self.date_label.setText(_translate("FieldSchedule", "Select Date:"))
        self.book_button.setText(_translate("FieldSchedule", "Book Field"))
