# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/TriKhiem/python-app/ui/field_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FieldItem(object):
    def setupUi(self, FieldItem):
        FieldItem.setObjectName("FieldItem")
        FieldItem.resize(280, 240)
        FieldItem.setMinimumSize(QtCore.QSize(280, 240))
        FieldItem.setMaximumSize(QtCore.QSize(280, 240))
        FieldItem.setStyleSheet("QWidget#FieldItem {\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: black;\n"
"    background: none;\n"
"    border-bottom: 1px solid #cccccc;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(FieldItem)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(parent=FieldItem)
        self.image_label.setMinimumSize(QtCore.QSize(280, 130))
        self.image_label.setMaximumSize(QtCore.QSize(280, 130))
        self.image_label.setStyleSheet("background-color: #f5f5f5;")
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.image_label)
        self.name_label = QtWidgets.QLabel(parent=FieldItem)
        self.name_label.setMinimumSize(QtCore.QSize(0, 30))
        self.name_label.setStyleSheet("padding-left: 5px;")
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.details_label = QtWidgets.QLabel(parent=FieldItem)
        self.details_label.setMinimumSize(QtCore.QSize(0, 50))
        self.details_label.setStyleSheet("padding-left: 5px;")
        self.details_label.setObjectName("details_label")
        self.verticalLayout.addWidget(self.details_label)
        self.view_button = QtWidgets.QPushButton(parent=FieldItem)
        self.view_button.setMinimumSize(QtCore.QSize(0, 30))
        self.view_button.setObjectName("view_button")
        self.verticalLayout.addWidget(self.view_button)

        self.retranslateUi(FieldItem)
        QtCore.QMetaObject.connectSlotsByName(FieldItem)

    def retranslateUi(self, FieldItem):
        _translate = QtCore.QCoreApplication.translate
        self.view_button.setText(_translate("FieldItem", "View More"))
