# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/TriKhiem/python-app/ui/time_slot.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimeSlot(object):
    def setupUi(self, TimeSlot):
        TimeSlot.setObjectName("TimeSlot")
        TimeSlot.resize(400, 60)
        TimeSlot.setMinimumSize(QtCore.QSize(0, 60))
        TimeSlot.setStyleSheet("QWidget#TimeSlot {\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton#book_button {\n"
"    background-color: #4CAF50;\n"
"}\n"
"\n"
"QPushButton#book_button:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton#book_button:disabled {\n"
"    background-color: #cccccc;\n"
"}\n"
"\n"
"QPushButton#booked_button {\n"
"    background-color: #f44336;\n"
"}\n"
"\n"
"QPushButton#booked_button:hover {\n"
"    background-color: #da190b;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(TimeSlot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.time_label = QtWidgets.QLabel(parent=TimeSlot)
        self.time_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.status_label = QtWidgets.QLabel(parent=TimeSlot)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout.addWidget(self.status_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.book_button = QtWidgets.QPushButton(parent=TimeSlot)
        self.book_button.setMinimumSize(QtCore.QSize(100, 30))
        self.book_button.setObjectName("book_button")
        self.horizontalLayout.addWidget(self.book_button)

        self.retranslateUi(TimeSlot)
        QtCore.QMetaObject.connectSlotsByName(TimeSlot)

    def retranslateUi(self, TimeSlot):
        _translate = QtCore.QCoreApplication.translate
        self.time_label.setText(_translate("TimeSlot", "00:00"))
        self.status_label.setText(_translate("TimeSlot", "Available"))
        self.book_button.setText(_translate("TimeSlot", "Book"))
